import Head from 'next/head'


export default function partners() {
    return (
        <div>    
        <Head>
        <title>TEDxIIMRanchi Partners</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600 shadow-2xl'>
            <h1>Our partners</h1>
        </div>
        </div>
    );
}
