import Head from "next/head";
import Link from "next/link";
import { AiFillLinkedin } from "react-icons/ai";

export default function team() {
  return (
    <div>
      <Head>
        <title>TEDxIIMRanchi Team</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-center gap-16 py-3 px-5">
        <h1 className="text-5xl">Our Team</h1>
        <div className="flex w-128 flex-wrap justify-around">
          <div className="shadow-2xl b-slate-600 w-64">
            <div className="m-4 w-50 h-50 p-28 hover:animate-pulse bg-gradient-to-b from-tedxred to-black rounded-2xl">
              <Link href="https://linkedin.com">
                <AiFillLinkedin />
              </Link>
            </div>
            <p className="p-2">
              Lorem Ipsum is simply dummy text of the printing and typesetting
              industry. Lorem Ipsum has been the industry's standard dummy text
              ever since the 1500s, when an unknown printer took a galley of
              type and scrambled it to make a type specimen book.
            </p>
          </div>
          <div className="shadow-2xl b-slate-600 w-64">
            <div className="m-4 w-50 h-50 p-28 hover:animate-pulse bg-gradient-to-b from-tedxred to-black rounded-2xl">
              <Link href="https://linkedin.com">
                <AiFillLinkedin />
              </Link>
            </div>
            <p className="p-2">
              Lorem Ipsum is simply dummy text of the printing and typesetting
              industry. Lorem Ipsum has been the industry's standard dummy text
              ever since the 1500s, when an unknown printer took a galley of
              type and scrambled it to make a type specimen book.
            </p>
          </div>
          <div className="shadow-2xl b-slate-600 w-64">
            <div className="m-4 w-50 h-50 p-28 hover:animate-pulse bg-gradient-to-b from-tedxred to-black rounded-2xl">
              <Link href="https://linkedin.com">
                <AiFillLinkedin />
              </Link>
            </div>
            <p className="p-2">
              Lorem Ipsum is simply dummy text of the printing and typesetting
              industry. Lorem Ipsum has been the industry's standard dummy text
              ever since the 1500s, when an unknown printer took a galley of
              type and scrambled it to make a type specimen book.
            </p>
          </div>
          <div className="shadow-2xl b-slate-600 w-64">
            <div className="m-4 w-50 h-50 p-28 hover:animate-pulse bg-gradient-to-b from-tedxred to-black rounded-2xl">
              <Link href="https://linkedin.com">
                <AiFillLinkedin />
              </Link>
            </div>
            <p className="p-2">
              Lorem Ipsum is simply dummy text of the printing and typesetting
              industry. Lorem Ipsum has been the industry's standard dummy text
              ever since the 1500s, when an unknown printer took a galley of
              type and scrambled it to make a type specimen book.
            </p>
          </div>

          <div className="shadow-2xl b-slate-600 w-64">
            <div className="m-4 w-50 h-50 p-28 hover:animate-pulse bg-gradient-to-b from-tedxred to-black rounded-2xl">
              <Link href="https://linkedin.com">
                <AiFillLinkedin />
              </Link>
            </div>
            <p className="p-2">
              Lorem Ipsum is simply dummy text of the printing and typesetting
              industry. Lorem Ipsum has been the industry's standard dummy text
              ever since the 1500s, when an unknown printer took a galley of
              type and scrambled it to make a type specimen book.
            </p>
          </div>
          <div className="shadow-2xl b-slate-600 w-64">
            <div className="m-4 w-50 h-50 p-28 hover:animate-pulse bg-gradient-to-b from-tedxred to-black rounded-2xl">
              <Link href="https://linkedin.com">
                <AiFillLinkedin />
              </Link>
            </div>
            <p className="p-2">
              Lorem Ipsum is simply dummy text of the printing and typesetting
              industry. Lorem Ipsum has been the industry's standard dummy text
              ever since the 1500s, when an unknown printer took a galley of
              type and scrambled it to make a type specimen book.
            </p>
          </div>
          <div className="shadow-2xl b-slate-600 w-64">
            <div className="m-4 w-50 h-50 p-28 hover:animate-pulse bg-gradient-to-b from-tedxred to-black rounded-2xl">
              <Link href="https://linkedin.com">
                <AiFillLinkedin />
              </Link>
            </div>
            <p className="p-2">
              Lorem Ipsum is simply dummy text of the printing and typesetting
              industry. Lorem Ipsum has been the industry's standard dummy text
              ever since the 1500s, when an unknown printer took a galley of
              type and scrambled it to make a type specimen book.
            </p>
          </div>
          <div className="shadow-2xl b-slate-600 w-64">
            <div className="m-4 w-50 h-50 p-28 hover:animate-pulse bg-gradient-to-b from-tedxred to-black rounded-2xl">
              <Link href="https://linkedin.com">
                <AiFillLinkedin />
              </Link>
            </div>
            <p className="p-2">
              Lorem Ipsum is simply dummy text of the printing and typesetting
              industry. Lorem Ipsum has been the industry's standard dummy text
              ever since the 1500s, when an unknown printer took a galley of
              type and scrambled it to make a type specimen book.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
