import Head from "next/head";
import Accordion from "./accordion";
import { accordionData } from "../public/members/members";

export default function team() {
  return (
    <div>
      <Head>
        <title>TEDxIIMRanchi Team</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-center gap-16 py-3 px-5">
        <h1 className="text-5xl">Our Team</h1>
        <div className="accordion">
          {accordionData.map(({ title, content }) => (
            <Accordion key={title} title={title} content={content} />
          ))}
        </div>
      </div>
    </div>
  );
}
